### ISSUE TITLE
Link to pre-trained model weights not working

### ISSUE THREAD

**Issue by rhornb** [kreshuklab/mouse-embryo-seg#1]
Dear @wolny, 

could you update the link to the pre-trained model weights (currently the page is not found when clicking on the link)?

Many thanks, 
Ruth

**Comment by wolny** [comment]
Dear @rhornb ,

thanks for raising the issue. The links to the pre-trained models for nuclei and membranes were indeed broken in the README. It is now fixed.

Cheers,
Adrian
